// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BhmvGXd9wRWKzqmFxEZONrJygnwXiWA',
    appId: '1:187481833333:web:555bd5bdead1f8785bdd3c',
    messagingSenderId: '187481833333',
    projectId: 'satu-desa-5a948',
    authDomain: 'satu-desa-5a948.firebaseapp.com',
    storageBucket: 'satu-desa-5a948.firebasestorage.app',
    measurementId: 'G-665P5CJRZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi0toX1my-eDeGN8AHJAwNvJ8VtAj3CSA',
    appId: '1:187481833333:android:28114d8142f231925bdd3c',
    messagingSenderId: '187481833333',
    projectId: 'satu-desa-5a948',
    storageBucket: 'satu-desa-5a948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnma6Go6Od42PhUUETRBDTz-6V1GCN-5E',
    appId: '1:187481833333:ios:90006257207f6d9b5bdd3c',
    messagingSenderId: '187481833333',
    projectId: 'satu-desa-5a948',
    storageBucket: 'satu-desa-5a948.firebasestorage.app',
    iosBundleId: 'com.example.satuDesa',
  );
}
